#import "../../helpers/template.typ": *
#import "helpers.typ": *
#import "@preview/unify:0.7.1": unit, qty
#import "@preview/zap:0.5.0"
#import "@preview/cetz:0.4.2"

#show: set_unit_number.with(4)
#show math.ell: varell

= Magnetic Fields and Electromagnetism

== Introduction to Magnetism

- Magnetism is a fundamental force of nature that arises from the motion of electric charges. 

- Magnetic fields are produced by moving charges (currents) and exert forces on other moving charges.

- There are three types of magnetic materials (see #link(<types-of-mm>)[Types of Magnetic Materials]): 
  - *ferromagnetic* materials (e.g. iron) are _strongly_ attracted to magnetic fields and can be permanently magnetized. 
    For this reason, they are often referred to as _"permanent magnets."_
  - *paramagnetic* materials are weakly attracted by magnetic fields
  - *diamagnetic* materials are weakly repelled by magnetic fields.

- A *magnet* is an object that produces a magnetic field. All magnets (that we know of) have two poles: a *north pole* and a *south pole*. 
  - Like poles repel each other, while opposite poles attract each other.
  - The magnetic field lines of a magnet form *closed loops* from the north pole to the south pole.

- The Earth itself is a magnet. Technically, the Earth's North pole is a magnetic south pole, for the north end of a compass needle is attracted to it.
  - The Earth's magnetic field is generated by the motion of molten iron in its outer core, which creates electric currents that produce the magnetic field.
  - Earth's magnetic field is extremely weak, around 50 #{sym.mu}T.

#pagebreak()

== Magnetic Fields and Magnetic Force

- Magnetic fields are produced by moving charges (currents). They exert forces on moving charges.
  - _Moving charges create magnetic fields. Magnetic fields exert forces on moving charges. This is the fundamental principle of electromagnetism._

- The magnetic field is represented by the vector $arrow(B)$, measured in _Teslas_ (T).
  - A 1 Tesla magnetic field exerts a force of 1 Newton on a 1 Coulomb point charge moving at $1 "m/s"$ *perpendicular* to the field. \
    #subtext[$unit("T") = unit("N s / C / m") = unit("kg / s^2 / A")$ in SI base units.]

- The direction of the magnetic field is the direction in which the north pole of a compass needle would point if placed in the field. 

- *Magnetic field lines* are a visual representation of the magnetic field.
  - The direction of the magnetic field at any point is tangent to the magnetic field line at that point
  - Stronger magnetic fields have more closely spaced field lines.
  - _Unlike_ electric field lines, magnetic field lines form _closed loops_!
    - _Outside_ of a bar magnet, magnetic field lines point from the north pole to the south pole.
    - _Inside_ of a bar magnet, magnetic field lines point from the south pole to the north pole.

#define("Magnetic Force")[
  Let $q$ be a charge moving with velocity $arrow(v)$ in a magnetic field $arrow(B)$. \ The *magnetic force* $arrow(F)_b$ on the charge is: $
    arrow(F)_b = q arrow(v) times arrow(B).
  $
]
- The magnetic force is always perpendicular to both the velocity of the charge and the magnetic field.

- The magnetic force does no work on the charge, since it is always perpendicular to the velocity of the charge.

- We can also calculate the magnetic force using current density $arrow(J)$: $
    dd(arrow(F)_b) = (arrow(J) times arrow(B)) dd(V) #h(1em) -> #h(1em) arrow(F)_b = integral.triple_E (arrow(J) times arrow(B)) dd(V).
  $

#define("Lorentz Force Law")[
  The *Lorentz force* $arrow(F)$ on a charge $q$ moving with velocity $arrow(v)$ in both electric and magnetic fields $arrow(E)$ and $arrow(B)$ is: $
    arrow(F) = arrow(F)_e + arrow(F)_b = q arrow(E) + q arrow(v) times arrow(B) = q (arrow(E) + arrow(v) times arrow(B)).
  $
]

The Lorentz force describes how charged particles behave in electromagnetic fields.

#pagebreak()

=== Magnetic Force on Current-Carrying Wires

- If charge is moving in a straight line (e.g. a straight wire), then the velocity is constant and we can write the magnetic force as: $
   arrow(F)_b = (q arrow(L))/t times arrow(B) = I arrow(L) times arrow(B).
$
  - Here, $arrow(L)$ is the length of a wire segment, and if it takes the charge $q$ a time $t$ to pass through the wire segment, then the current $I = q slash t$.

  - The magnetic force on a charge moving through a wire segment is proportional to the length of that segment, the current through that segment, and the magnetic field strength.

  - For a wire that isn't straight, we can divide the wire into tiny segments of length $dd(arrow(ell))$ to get:
    $
      dd(arrow(F)_b) = I dd(arrow(ell)) times arrow(B) #h(1em) -> #h(1em) arrow(F)_b = integral_C I dd(arrow(ell)) times arrow(B).
    $

- A *coil* has no net magnetic force on it, since the magnetic forces on opposite sides of the coil cancel each other out ($display(integral.cont I dd(arrow(ell)) times arrow(B)) = 0$). However, a coil can still _produce_ a magnetic field.

- A *solenoid* is a long coil of wire (a wire formed from multiple coils). The magnetic field inside a solenoid is approximately uniform and parallel to the axis of the solenoid, while the magnetic field outside a solenoid is weak and non-uniform.

#pagebreak()

== Magnetic Dipoles

- _Recall:_ an electric dipole consists of two equal and opposite charges separated by a small distance.

- Unlike charges which can exist independently, magnetic poles always come in pairs #footnote[Although we aren't able to _disprove_ magnetic monopoles, none have been discovered.] (north and south). Thus, all magnets are *magnetic dipoles*.

- The magnetic field of a magnetic dipole is similar to the electric field of an electric dipole, but with some differences:

  - The magnetic field lines of a magnetic dipole form closed loops, while the electric field lines of an electric dipole start at the positive charge and end at the negative charge.
  
  - The magnetic field of a magnetic dipole decreases with distance by the cube ($B prop 1 slash r^3$), while the electric field of an electric dipole decreases with distance by the square ($B prop 1 slash r^2$).

- The *magnetic dipole moment* $arrow(mu)$ of a magnetic dipole is a vector that points from the south pole to the north pole.

  In a region enclosed by a current-carrying coil with area $A$, the magnetic dipole moment is:
  $
    arrow(mu) = I A hat(n) = I underbrace(arrow(A), A hat(n)).
  $
  where:
  - $I$ is the current through the coil
  - $A$ is the area of the coil
  - $hat(n)$ is the unit vector perpendicular to the plane of the coil, pointing in the direction given by the right-hand rule (curl your hands in the direction of current, and your thumb will point in $hat(n)$)

  For a solenoid with $N$ loops, the magnetic dipole moment is: $
    arrow(mu) = N I arrow(A).
  $

- A magnetic field exerts a torque $arrow(tau)$ on a magnetic dipole: $
    arrow(tau) = arrow(mu) times arrow(B).
  $
  The magnetic dipole will experience a torque that tends to align it with the magnetic field. 
  
  This means that there is the potential for work to be done to align a magnetic dipole with a magnetic field, given by the potential energy $U_mu$ of the dipole:
  $
    U_mu = -arrow(mu) dot arrow(B).
  $

In summary,
- if we place a current-carrying coil in a magnetic field, it will experience a torque that tends to align it with the field.
- the potential energy associated with this dipole is the work required to align the dipole with the field.

#pagebreak()

== Magnetic Fields from Moving Charges

=== Biot-Savart Law

Whereas the formulas above allow us to find the magnetic force on a moving charge in an _existing_ magnetic field (the first part of electromagnetism), moving charges also create their _own_ magnetic fields (the second part of electromagnetism). 

The *Biot-Savart Law* allows us to calculate the magnetic field _created_ by a moving charge or current.

#define("Biot-Savart Law")[
  Let $I$ be the current through a small wire segment $dd(arrow(ell))$. The magnetic field $dd(arrow(B))$ at a point $P$ due to this wire segment is: $
    dd(arrow(B)) = (mu_0)/(4pi) (I dd(arrow(ell)) times hat(r))/r^2
  $
  where:
  - $mu_0 = 4pi dot 10^(-7) #unit("N/A^2")$ is the *permeability of free space*
  - $hat(r)$ is the unit vector from the wire segment to point $P$
  - $r$ is the distance from the wire segment to point $P$

  If a wire is curved in a path $C$, then the total magnetic field at point $P$ is: $
    arrow(B) = (mu_0)/(4pi) integral_C (I dd(arrow(ell)) times hat(r))/r^2.
  $

  For point charge $q$ with velocity $arrow(v)$, the Biot-Savart Law can be simplified as: $
    arrow(B) = (mu_0)/(4pi) (q arrow(v) times hat(r))/r^2.
  $
]

By the definition of the cross product, the magnitude of the magnetic field contribution from the wire segment is: $
  abs(dd(arrow(B))) = dd(B) = (mu_0)/(4pi) (I dd(ell) sin theta)/r^2
$ where $theta$ is the angle between $dd(arrow(ell))$ and $hat(r)$.

#example("Magnetic field from a straight current-carrying wire")[
  An infinitely long, straight wire carries a current $I$. What is the magnetic field $arrow(B)$ at a point $P$ a distance $h$ away from the wire?
  #lorange

  By the Biot-Savart Law, the magnetic field at point $P$ is: $
    arrow(B) = (mu_0)/(4pi) integral_"wire" (I dd(arrow(ell)) times hat(r))/r^2.
  $

  Say that the wire lies along the $x$-axis, and point $P$ is at coordinates $(0, h)$. 
  Along the wire, $I$ is constant, so:
  $
    arrow(B) = (mu_0 I)/(4pi) integral_"wire" (dd(arrow(ell)) times hat(r))/r^2.
  $

  Evaluate $dd(arrow(ell)) times hat(r)$ using the definition of the cross product:
  $
    dd(arrow(ell)) times hat(r) = dd(ell) sin theta thin hat(n).
  $

  Notice that $hat(n)$ is perpendicular to the plane formed by $dd(arrow(ell))$ and $hat(r)$, so it is constant. However, $sin theta$ is _not_ constant. Together, we get:
  $
    arrow(B) = (mu_0 I hat(n))/(4pi) integral_(-oo)^(+oo) (dd(x) sin theta)/r^2.
  $

  Using trigonometry, $cpurple(sin theta = h slash r)$ and $cblue(r^2 = x^2 + h^2)$. Thus, $
    arrow(B) &= (mu_0 I hat(n))/(4pi) integral_(-oo)^(+oo) (dd(x) thin cpurple(h))/(cpurple(sqrt(x^2 + h^2)) cblue((x^2 + h^2))) \
    & = (mu_0 I h hat(n))/(4pi) integral_(-oo)^(+oo) dd(x)/(x^2 + h^2)^(3 slash 2).
  $

  Evaluating the integral gives: $
    arrow(B) = (mu_0 I h hat(n))/(4pi) (2 / h^2) = cgreen((mu_0 I)/(2pi h) hat(n)).
  $
]

#pagebreak()

=== Ampere's Law

The Biot-Savart Law allows us to calculate the magnetic field created by a current, but it can be difficult to apply in practice.

*Ampere's Law* provides an alternative way to calculate magnetic fields, especially for cases with high symmetry.

#define("Ampere's Law")[
  Let $C$ be a closed, often imaginary loop, called an *Amperian loop*. Let $I_"enclosed"$ be the net current passing through any surface enclosed #footnote[by "enclosed", we mean that the surface has a boundary defined by $C$. That is,  if $S$ is the surface, $partial S equiv C$.]
  by $C$. *Ampere's Law* states that:
  $
    integral.cont_C arrow(B) dot dd(arrow(s)) = mu_0 I_"enclosed".
  $

  We often call the quantity $display(integral.cont_C arrow(B) dot dd(arrow(s)))$ the *magnetic circulation*
  over $C$. Thus, Ampere's Law states that the magnetic circulation around a closed loop is proportional to the net current passing through the area enclosed by that loop.
]

#example("Magnetic field from a straight current-carrying wire, revisited")[
  A long, straight wire with radius $R$ carries a current $I$. What is the magnetic field $arrow(B)$ at a point $P$ a distance $r$ away from the center of the wire?

  #lorange

  Create a circular Amperian loop of radius $r > R$ centered on the wire. By symmetry, the magnetic field $arrow(B)$ has the same magnitude at every point on the loop and is tangent to the loop, so $B$ is constant.
  
  Thus, by Ampere's Law: $
    integral.cont_C arrow(B) dot dd(arrow(s)) = B integral.cont_C dd(s) = B (2pi r) = mu_0 I.
  $
  Solving for $B$ gives: $
    cgreen(B = (mu_0 I)/(2pi r)) "for" r > R.
  $
  This is the same result we would get from the Biot-Savart Law, but Ampere's Law is much easier to apply in this case due to the symmetry of the problem. 

  Ampere's Law also allows us to find the magnetic field inside the wire (where $r < R$), which is: $
    cgreen(B = (mu_0 I r)/(2pi R^2)) "for" r < R.
  $
]

#pagebreak()

=== Magnetic Fields of Solenoids

- A solenoid is a wire formed from multiple coils, called *turns*. 
  - The magnetic field inside a solenoid is approximately uniform and parallel to the axis of the solenoid
  - The magnetic field outside a solenoid is weak and non-uniform.

- The magnetic field _inside_ a solenoid with current $I$ can be calculated using Ampere's Law: 
  - Consider a rectangular Amperian loop that extends inside and outside the solenoid.

  - The magnetic field outside the solenoid is negligible, so the contribution to the line integral from the outside part of the loop is approximately zero.

  - The magnetic field inside the solenoid is approximately uniform, so the contribution to the line integral from the inside part of the loop is approximately $B L$, where $L$ is the length of the section of the Amperian loop that is inside the solenoid.

  - Along the sides, the magnetic field is perpendicular to the path of integration, so the contribution to the line integral from the sides is zero.

  - If our loop encloses $N$ turns of the solenoid, then the total current enclosed by the loop is $N I$.

  Thus, by Ampere's Law: $
    integral.cont_C arrow(B) dot dd(arrow(ell)) = B L = mu_0 N I #h(1em) -> #h(1em) cgreen(B = (mu_0 N I)/L).
  $ 

- We call $n = N slash L$ the *turn density* of the solenoid, which is the number of turns per unit length. \
  This allows us to rewrite the formula for the magnetic field inside a solenoid as: $
    cgreen(B = mu_0 n I).
  $

=== Differential Form of Ampere's Law

Using Stokes' Theorem and the integral definition of current density, we can rewrite Ampere's Law in differential form: $
  integral.cont_C arrow(B) dot dd(arrow(ell)) &= mu_0 I_"enclosed" \
  integral.double_S (grad times arrow(B)) dot dd(arrow(A)) &= mu_0 integral.double_S arrow(J) dot dd(arrow(A)) \
  cgreen(grad times arrow(B) &= mu_0 arrow(J)).
$

#define("Ampere's Law (Differential Form)")[
  Let a current density $arrow(J)$ produce a magnetic field $arrow(B)$. *Ampere's Law* in differential form states that: $
    grad times arrow(B) = mu_0 arrow(J).
  $
  That is, the _curl_ of the magnetic field is proportional to the current density that produces it. 
]

=== Extension: Magnetic Vector Potential <magnetic-vector-potential>

_Recall:_ the electric field $arrow(E)$ can be expressed using the gradient of the _electric potential_ $V$: $arrow(E) = -grad V.$

Similarly, the magnetic field $arrow(B)$ can be expressed as the curl of a vector field called the *magnetic vector potential* $arrow(A)$: $
  arrow(B) = grad times arrow(A).
$

_Recall that the divergence of the magnetc field is zero ($grad dot arrow(B) = 0$, Gauss' Law for Magnetism), which means that the magnetic field is guaranteed to be the curl of some vector field._

#define("Magnetic Vector Potential")[
  The *magnetic vector potential* $arrow(A)$ is a vector field whose curl gives the magnetic field $arrow(B)$: $
    arrow(B) = grad times arrow(A).
  $
]
- The magnetic vector potential is a mathematical tool that allows us to calculate the magnetic field in certain situations, especially when dealing with complex geometries or time-varying fields.

- The magnetic vector potential has units of $"T m" equiv "Wb/m"$.

- The magnetic vector potential is _not_ unique, since we can add the gradient of any scalar field
  to $arrow(A)$ without changing the magnetic field (since the curl of a gradient is zero)

#define("Biot-Savart Law (Vector Potential Form)")[
  // Let $arrow(J)$ be a current density in a region $V$ that has space-varying magnetic field. 
  // The magnetic vector potential $arrow(A)$ at any point $P$ in $V$ is given by: $
  //   arrow(A) = (mu_0)/(4pi) integral.triple_V arrow(J) / r dd(V),
  // $
  // where $r$ is the distance from point of integration to $P$. (That is, the integral body can be written as $arrow(J) slash r(x, y, z) dd(x) dd(y) dd(z)$.)

  Let $I$ be the current through a wire segment $dd(arrow(ell))$. The magnetic vector potential $dd(arrow(A))$ at a point $P$ due to this wire segment is: $
    dd(arrow(A)) = mu_0/(4pi) (I dd(arrow(ell))) / r,
  $
  where $r$ is the distance from the wire segment to point $P$.
]

Ampere's Law in magnetic vector potential form can be derived by substituting $arrow(B) = grad times arrow(A)$: $
  grad times (grad times arrow(A)) &= mu_0 arrow(J) \
  grad cancel((grad dot arrow(A))) - nabla^2 arrow(A) &= mu_0 arrow(J) \
  cgreen(nabla^2 arrow(A) &= -mu_0 arrow(J)).
$

Also, by Stokes' Theorem, if $C$ is a closed loop and $S$ is any surface with boundary $C$, then: $
  integral.cont_C arrow(A) dot dd(arrow(ell)) = integral.double_S (grad times arrow(A)) dot dd(arrow(A)) = integral.double_S arrow(B) dot dd(arrow(A)) = Phi_B.
$
_The circulation of the magnetic vector potential around a closed loop is equal to the #link(<mflux>)[magnetic flux] $Phi_B$ through any surface bounded by that loop._

#pagebreak()

== Magnetic Properties of Materials <types-of-mm>

=== Magnetization and the $H$-field

At the microscopic level, electrons have a property called *spin* that gives them an intrinsic magnetic dipole moment. 
- Most electrons are paired up with another electron of opposite spin, so their magnetic dipole moments cancel each other out.
- Some materials have unpaired electrons, resulting in a _net dipole moment_, which can interact (i.e., align) with external magnetic fields.

The density of these microscopic dipoles is called the *magnetization* of the material:
#define("Magnetization")[
  The *magnetization* or *magnetic polarization* $arrow(M)$ is the net magnetic dipole moment per unit volume:
  $
    arrow(M) = dv(arrow(mu), V) #h(1em) -> #h(1em) arrow(mu) = integral.triple_V arrow(M) dd(V).
  $
  For this reason, magnetization is sometimes called _magnetic moment density_.
]

- An unmagnetized object has $arrow(M) = arrow(0)$ everywhere (i.e., dipoles cancel) 
- Magnetization is a vector quantity, measured in units of $"A/m"$.

While $arrow(M)$ is the internal or _bound_ magnetization of the material, an external or _applied_
magnetic field created by other currents can realign the dipoles. The applied magnetic field
is called the *$H$-field* or *magnetic field intensity*, denoted $arrow(H)$:

#define([Magnetic Field Intensity ($H$-field)])[
  The net magnetic field $arrow(B)$ inside a material is proportional to the sum of the applied field $arrow(H)$ and the field created by the magnetization of the material $arrow(M)$:
  $
    arrow(B) = mu_0 (arrow(H) + arrow(M)).
  $
  The constant of proportionality $mu_0$ is the permeability of free space.
]
- In the above equation, we are strictly looking at the magnetic field _inside_ the material.
- The $H$-field is measured in units of $"A/m"$, the same as magnetization.
- The $H$-field is the magnetic field that would exist in the absence of any magnetization. It is the field that we apply to a material to induce magnetization.

#pagebreak()

=== Linear Magnetic Materials and Magnetic Permeability

A *linear magnetic material* is one where its magnetization is proportional to the $H$-field:
$
  arrow(M) = chi arrow(H) "for a linear magnetic material",
$
where the constant of proportionality $chi$ is called the *magnetic susceptibility* of the material. It is a dimensionless quantity that measures how much a material becomes magnetized in response to an applied magnetic field. Most materials are approximately #footnote[
  Most materials are approximately linear for sufficiently small $H$-fields, 
  but some materials (e.g. ferromagnets) can become noticeably nonlinear at higher field strengths.
] linear.

- For certain materials, $chi$ can be negative! This means that the material becomes magnetized in the _opposite_ direction of the applied field (see #link(<diamagnetism>)[diamagnetism]). 

- If $abs(chi)$ is high, then the material is easily able to form internal magnetic fields in response to an external magnetic field.

Since $arrow(M) = chi arrow(H)$, then for a linear magnetic material: $
  arrow(B) = mu_0 (arrow(H) + arrow(M)) = mu_0 (arrow(H) + chi arrow(H)) = mu_0 (1 + chi) arrow(H).
$

The *absolute magnetic permeability* $mu$ is the constant of proportionality between $arrow(B)$ and $arrow(H)$:
$
  arrow(B) = mu arrow(H).
$

Magnetic permeability measures how strongly a material _supports_ an applied magnetic field.
It is measured in units of $"T m/A"$. The *relative magnetic permeability* $mu_r$ of a material is the ratio of its absolute permeability to the permeability of free space:
$
  mu_r =^"def" mu / mu_0 = (mu_0 (1 + chi)) / mu_0 = 1 + chi.
$
#rsubtext[$kappa$ or $kappa_m$ can be used to denote $mu_r$ (similar to how either $epsilon_r$ or $kappa$ can be used for relative permittivity).]

// ==== Bound Currents

// A spatially non-uniform magnetization acts as an effective source of magnetic field. The microscopic current loops of aligned dipoles do not cancel perfectly at the boundaries of magnetized regions, giving rise to *bound currents*:

// - *Volume bound current density:* $arrow(J)_b = grad times arrow(M)$
// - *Surface bound current density:* $arrow(K)_b = arrow(M) times hat(n)$

// The total magnetic field satisfies:
// $
//   grad times arrow(B) = mu_0 (arrow(J)_"free" + arrow(J)_b) = mu_0 (arrow(J)_"free" + grad times arrow(M))
// $
// which can be rearranged to:
// $
//   grad times (arrow(B) / mu_0 - arrow(M)) = arrow(J)_"free".
// $

// #note[
//   The free current $arrow(J)_"free"$ is the ordinary conduction current (e.g.\ from electrons in a wire).
//   Bound currents $arrow(J)_b$ arise entirely from the magnetization of the material and require no external circuit.
// ]

// The rearranged equation above motivates defining the *magnetic field intensity* (or *$H$-field*):

// #define([Magnetic Field Intensity ($H$-field)])[
//   $
//     arrow(H) = arrow(B) / mu_0 - arrow(M) #h(1em) -> #h(1em) cgreen(arrow(B) = mu_0 (arrow(H) + arrow(M))).
//   $
// ]

// With this definition, Ampere's Law generalizes cleanly to matter:

// #define("Ampere's Law for Magnetic Materials")[
//   $
//     grad times arrow(H) = arrow(J)_"free" #h(2em) <=> #h(2em) integral.cont_C arrow(H) dot dd(arrow(s)) = I_"free, enc".
//   $
//   $arrow(H)$ is sourced _only_ by free currents. The material's magnetic response is entirely encoded in $arrow(M)$, which need not be known to apply this law.
// ]

// - In free space $arrow(M) = arrow(0)$, so $arrow(H) = arrow(B) slash mu_0$ and this reduces to the ordinary Ampere's Law $grad times arrow(B) = mu_0 arrow(J)$.
// - $arrow(B)$ is the physical field that exerts forces on charges; $arrow(H)$ is the auxiliary field that simplifies calculations when free currents are the known quantity.

// ==== Linear Response
// For *linear* magnetic materials, the magnetization is proportional to the applied H-field:
// $
//   arrow(M) = chi arrow(H).
// $
// Substituting into $arrow(B) = mu_0 (arrow(H) + arrow(M))$:
// $
//   arrow(B) = mu_0 (1 + chi) arrow(H) = cgreen(mu_r mu_0 arrow(H) = mu arrow(H)).
// $
// This connects the microscopic magnetization $arrow(M)$ to the macroscopic material constants $chi$, $mu_r$, and $mu$ described in the next section.

=== Types of Magnetic Materials

Magnetic materials are generally classified in terms of their magnetic susceptibility $chi$: 

- *Paramagnetic* materials such as aluminum have a small positive magnetic susceptibility ($chi > 0$), meaning they are weakly attracted to magnetic fields.

- *Diamagnetic* materials such as copper have a small negative magnetic susceptibility ($chi < 0$), meaning they are weakly repelled by magnetic fields. <diamagnetism>

- *Ferromagnetic* materials such as iron have a large positive magnetic susceptibility ($chi >> 0$), meaning they are strongly attracted to magnetic fields and can retain magnetization even after the external field is removed (_"permanent magnets"_).
  - Ferromagnetic materials are made up of small regions called *magnetic domains*, where the magnetic moments of atoms are aligned in the same direction. When an external magnetic field is applied, these domains can grow and align with the field, leading to a strong overall magnetization.

// - *Magnetic permeability* $mu$ measures how easily a material supports a magnetic field. It is written $mu = mu_r mu_0$, where $mu_r$ is the dimensionless *relative permeability* of the material.

// - *Magnetic susceptibility* $chi_m$ relates the magnetization of a material to the applied field: $mu_r = 1 + chi_m$. Materials with $chi_m > 0$ are magnetized in the same direction as the applied field; those with $chi_m < 0$ oppose it.

// - *Paramagnetism*: $chi_m$ is small and positive ($mu_r$ slightly above 1). Individual atomic dipoles weakly align with an external field but thermal motion prevents strong, permanent magnetization.

// - *Diamagnetism*: $chi_m$ is small and negative ($mu_r$ slightly below 1). Induced orbital currents weakly oppose an external field. All materials are diamagnetic at some level; it is usually masked by stronger effects.

// - *Ferromagnetism*: $mu_r >> 1$ (up to $tilde 10^4$ or more). Atoms in *magnetic domains* — small regions with uniformly aligned dipoles — switch orientation to align with an external field, producing a dramatically amplified response. Ferromagnets (iron, nickel, cobalt) can retain magnetization after the external field is removed (*permanent magnets*).


#pagebreak()